{{ if .Values.subnetIDs }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "{{.Values.cluster_name}}-{{regexReplaceAll "\\.+" .Values.instance_type ""}}"
spec:
  clusterName: "{{.Values.cluster_name}}"
  replicas: 2
  template:
    spec:
      clusterName: "{{.Values.cluster_name}}"
      bootstrap:
        dataSecretName: ""
      # clusterName: "{{.Values.cluster_name}}"
      infrastructureRef:
        name: "{{.Values.cluster_name}}-{{regexReplaceAll "\\.+" .Values.instance_type ""}}"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: "{{.Values.cluster_name}}-{{regexReplaceAll "\\.+" .Values.instance_type ""}}"
spec:
  instanceType: {{.Values.instance_type}}
  diskSize: 50
  {{- with .Values.subnetIDs }}
  subnetIDs:
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  scaling:
    minSize: 1
    maxSize: 5
{{- end }}
